set_property PACKAGE_PIN G2 [get_ports Vaux4_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux4_v_n]
set_property PACKAGE_PIN M3 [get_ports {TOF_out[0]}]
set_property PACKAGE_PIN L3 [get_ports {TOF_out[1]}]
set_property PACKAGE_PIN A16 [get_ports {TOF_out[2]}]
set_property PACKAGE_PIN K3 [get_ports {TOF_out[3]}]
set_property PACKAGE_PIN C15 [get_ports {TOF_out[4]}]
set_property PACKAGE_PIN H1 [get_ports {TOF_out[5]}]
set_property PACKAGE_PIN A15 [get_ports {TOF_out[6]}]
set_property PACKAGE_PIN B15 [get_ports {TOF_out[7]}]
set_property PACKAGE_PIN A14 [get_ports {TOF_out[8]}]
set_property PACKAGE_PIN J3 [get_ports {TOF_out[9]}]
set_property PACKAGE_PIN J1 [get_ports {TOF_out[10]}]
set_property PACKAGE_PIN K2 [get_ports {TOF_out[11]}]
set_property PACKAGE_PIN L1 [get_ports {TOF_out[12]}]
set_property PACKAGE_PIN V8 [get_ports start]
set_property PACKAGE_PIN P1 [get_ports TOF_ready]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TOF_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports TOF_ready]

set_property IOSTANDARD LVCMOS33 [get_ports Vaux4_v_p]

set_property IOSTANDARD LVCMOS33 [get_ports clkOut]
set_property PACKAGE_PIN N2 [get_ports clkOut]
set_property PACKAGE_PIN N1 [get_ports drdy_latch]
set_property IOSTANDARD LVCMOS33 [get_ports drdy_latch]

set_property PACKAGE_PIN L2 [get_ports clk100M]
set_property PACKAGE_PIN P3 [get_ports drdy_Out]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M]
set_property IOSTANDARD LVCMOS33 [get_ports drdy_Out]

set_property PACKAGE_PIN N2 [get_ports clk12MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk12MHz]
